### ISSUE TITLE
Saving .obj files and reading .pkl files

### ISSUE THREAD

**Issue by nshreyasvi** [yw0208/W-HMR#9]
Hello,

Thank you for the amazing work. I was trying to run the `--save_obj` flag but it doesn't seem to save any output SMPL meshes. I further checked that there has been `mesh_filename` variable that has been defined in the code but it doesn't seem to use trimesh to save the output arrays in them.

I furthermore, tried to re-open the `.pkl` files. However, it seems that they don't follow the standard SMPL format and don't have any keys such as `betas`, `body_pose` or 'transl`. I wanted to know how can I obtain the output SMPL's through this library.

**Comment by yw0208** [comment]
Hi, I just pushed new codes. Now you can use `--save_obj` to save SMPL meshes.

As for `.pkl` files, they contain output by W-HMR. You can refer to [whmr.py](https://github.com/yw0208/W-HMR/blob/6dd6c49953ba56deca02be56da64bfe1814c9c24/models/whmr.py#L665). BTW, betas are shape, body_pose is global pose and transl can be calculated through pred_cam_t.

**Comment by nshreyasvi** [comment]
Hello, I was trying to run the script but I get the following error:
```
ModuleNotFoundError: No module named 'yolov3'
```
I checked in the `environment.yml` file and there seems to be a `yolov3==0.1` dependency there but there doesn't seem to be a package available with this configuration. Also, the minimum version is `yolov3==1.7` which requires `python=3.6` and it leads to even more package conflicts. Could you let me know where did you install the yolov3 package ?

**Comment by nshreyasvi** [comment]
Hello, Thank you for your response. I tested the code but I am currently getting the following error:
```
Traceback (most recent call last):
  File "C:\Users\snatraj\Downloads\Projects\W-HMR\demo\whmr_demo.py", line 172, in <module>
    main(args)
  File "C:\Users\snatraj\Downloads\Projects\W-HMR\demo\whmr_demo.py", line 76, in main
    detections = tester.run_detector(input_image_folder)
  File "C:\Users\snatraj\Downloads\Projects\W-HMR\.\demo\tester.py", line 70, in run_detector
    mot = MPT(
  File "C:\Users\snatraj\anaconda3\envs\hmr\lib\site-packages\multi_person_tracker\mpt.py", line 52, in __init__
    self.detector = YOLOv3(
  File "C:\Users\snatraj\anaconda3\envs\hmr\lib\site-packages\yolov3\yolo.py", line 32, in __init__
    download_url(url, outdir)
  File "C:\Users\snatraj\anaconda3\envs\hmr\lib\site-packages\yolov3\yolo.py", line 11, in download_url
    subprocess.call(cmd)
  File "C:\Users\snatraj\anaconda3\envs\hmr\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\snatraj\anaconda3\envs\hmr\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\snatraj\anaconda3\envs\hmr\lib\subprocess.py", line 1436, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
Could you let me know how can I resolve this?

**Comment by yw0208** [comment]
Hi, I didn't run this project on Windows before. So I am not sure how to fix it. But I find  this [issue](https://github.com/carlosedubarreto/vibe_win_install/issues/5#issuecomment-773526047), which may help you.

**Comment by nshreyasvi** [comment]
Hello, Thank you for the comment and sorry for the delays in reverting back. Do you think that this issue might arise from the YOLOv3 Library. I am not sure which version of YOLOv3 library you used as I currently am doing `pip install git+https://github.com/eriklindernoren/PyTorch-YOLOv3.git`. However, I see that the yolov3 library requires pytorch 1.12.1

Was it the same YOLOv3 library that you used?

**Comment by yw0208** [comment]
> Hello, Thank you for the comment and sorry for the delays in reverting back. Do you think that this issue might arise from the YOLOv3 Library. I am not sure which version of YOLOv3 library you used as I currently am doing `pip install git+https://github.com/eriklindernoren/PyTorch-YOLOv3.git`. However, I see that the yolov3 library requires pytorch 1.12.1
> 
> Was it the same YOLOv3 library that you used?

Hi，I used this version `git+https://github.com/mkocabas/yolov3-pytorch.git`

**Comment by nshreyasvi** [comment]
Hello, Thank you, I fixed the issue by installing W-HMR on WSL. There was an issue with loading CUDA but I solved it by adding `export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH` to the `.basrc` file. It seems to work perfectly now.
I had a few secondary questions regarding the tool. 
- I tried to use the Male and Female models by renaming them as the neutral model. Does the performance for mesh recovery change if I do that or does it make it more accurate?
- In case if I wanted to implement this over data for children, is there [SMIL](https://ps.is.mpg.de/code/skinned-multi-infant-linear-model-smil) but for kids (around age of 5-10 years old). That can be used for accurate mesh recovery for them?

**Comment by yw0208** [comment]
> Hello, Thank you, I fixed the issue by installing W-HMR on WSL. There was an issue with loading CUDA but I solved it by adding `export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH` to the `.basrc` file. It seems to work perfectly now. I had a few secondary questions regarding the tool.
> 
> * I tried to use the Male and Female models by renaming them as the neutral model. Does the performance for mesh recovery change if I do that or does it make it more accurate?
> * In case if I wanted to implement this over data for children, is there [SMIL](https://ps.is.mpg.de/code/skinned-multi-infant-linear-model-smil) but for kids (around age of 5-10 years old). That can be used for accurate mesh recovery for them?

Hi, thanks for your question. Here are my answers.
* For W-HMR, it would not be obvious but indeed be a little more accurate.
* W-HMR can't be directly to recover children. The body proportions of children are very different from those of adults. If you directly use W-HMR to recover a child's mesh, the reconstructed body will still be like an adult. You should train another model with children mesh model (i.e., SMIL and SMPL-X kid).

**Comment by nshreyasvi** [comment]
Hello,
Thank you so much for the answers to the previous questions.  I am currently running an analysis of the model output. I believe that I was getting an error when I was running analysis using
```
            if not self.args.no_save:
                save_f = os.path.join(
                    output_path, 'whmr_results',
                    'og_'+os.path.basename(img_fname).replace(img_fname.split('.')[-1], 'pkl')
                )
                joblib.dump(output, save_f)
```
So, I replaced it and used pickle instead:
```
            with open(str(output_path)+'/whmr_results/'+os.path.basename(img_fname).replace(img_fname.split('.')[-1], 'pkl'), 'wb') as smpl_f:
                pickle.dump(output, smpl_f)
```
I believe this is giving me the correct keys that I can use. However, when I am checking the dimensions of output `global_pose` and `local_pose`. I get the shape `(1,72)`. I was a bit confused as which one should I take for analysis and should it not be of dimensions `(1, 23, 3, 3)`?

**Comment by yw0208** [comment]
> Hello, Thank you so much for the answers to the previous questions. I am currently running an analysis of the model output. I believe that I was getting an error when I was running analysis using
> 
> ```
>             if not self.args.no_save:
>                 save_f = os.path.join(
>                     output_path, 'whmr_results',
>                     'og_'+os.path.basename(img_fname).replace(img_fname.split('.')[-1], 'pkl')
>                 )
>                 joblib.dump(output, save_f)
> ```
> 
> So, I replaced it and used pickle instead:
> 
> ```
>             with open(str(output_path)+'/whmr_results/'+os.path.basename(img_fname).replace(img_fname.split('.')[-1], 'pkl'), 'wb') as smpl_f:
>                 pickle.dump(output, smpl_f)
> ```
> 
> I believe this is giving me the correct keys that I can use. However, when I am checking the dimensions of output `global_pose` and `local_pose`. I get the shape `(1,72)`. I was a bit confused as which one should I take for analysis and should it not be of dimensions `(1, 23, 3, 3)`?

Hi, different shapes depend on different rotation representations. 

When the shape is '(1, 72)' or (1, 24, 3), joint rotation is represented by the axis angle.  When the shape is '(1, 23, 3, 3)' or '(1, 24, 3, 3)' (which with human orientation), joint rotation is represented by the rotation matrix. You can check this conversion in [geometry.py](https://github.com/yw0208/W-HMR/blob/main/utils/geometry.py)

**Comment by nshreyasvi** [comment]
Hello,
Thank you a lot for the quick response. I would like to know if it is possible to convert the `(1, 23, 3, 3)` into `(1,72)` dimensions as well as extract `global_pose` using the input? If you could direct me to the function that does that it would be great.

**Comment by yw0208** [comment]
> Hello, Thank you a lot for the quick response. I would like to know if it is possible to convert the `(1, 23, 3, 3)` into `(1,72)` dimensions as well as extract `global_pose` using the input? If you could direct me to the function that does that it would be great.

You can use [rotation_matrix_to_angle_axis](https://github.com/yw0208/W-HMR/blob/6dd6c49953ba56deca02be56da64bfe1814c9c24/utils/geometry.py#L54) and get '(1, 23, 3)'. Reshape it and get `(1, 69)`. If you want `(1, 72)`, you need add global orientation just like my `global_pose`.

**Comment by nshreyasvi** [comment]
Hello, thank you so much for the response. I was able to convert the files. In order to benchmark the model, I am trying to generate the `(1, 24, 3)` body pose and wanted to know how can I get the `transl` value from the output keys? I believe you already mentioned that it can be calculated through `pred_cam_t` but I am not sure if it is the `transl` value?

**Comment by yw0208** [comment]
> Hello, thank you so much for the response. I was able to convert the files. In order to benchmark the model, I am trying to generate the `(1, 24, 3)` body pose and wanted to know how can I get the `transl` value from the output keys? I believe you already mentioned that it can be calculated through `pred_cam_t` but I am not sure if it is the `transl` value?

You can find the method to get the translation in [whmr.py.](https://github.com/yw0208/W-HMR/blob/6dd6c49953ba56deca02be56da64bfe1814c9c24/models/whmr.py#L154). You can search for _Tz_ or _pred_cam_t_, and then you will know how to calculate the translation. Note that the translation obtained by our method cannot be used as a global coordinate.

**Comment by nshreyasvi** [comment]
Hello, Thank you for the quick response. My main goal was to calculate the `pose` vertices in `(1, 24, 3)` format to compare with MoCap. For that, I have to convert it from the `(1,72)` format using the SMPL method. I wanted to know if `pred_cam_t` is the `transl` value as they both seem to have the same shape and it seems to be the global orientation used [here](https://github.com/yw0208/W-HMR/blob/6dd6c49953ba56deca02be56da64bfe1814c9c24/models/whmr.py#L165). I was currently using the `pred_cam_t` and `betas` to change the shape from `(1, 72)` to `(1, 24, 3)` using the method described in slide 21 [here](https://files.is.tue.mpg.de/black/talks/SMPL-made-simple-FAQs.pdf)

**Update: I realised we don't need `pred_cam_t` for computing the pose, only the betas and local pose. I did it to convert `(1,72)` to `(1,24,3)` and it seems to provide accurately the local pose that I will try to use for benchmarking.**
```
elif input_type == 'whmr':
    print("WHMR Input")
    betas = torch.from_numpy(data['shape'])
    pred_pose = torch.from_numpy(data['local_pose'])

    # Load SMPL model and get predicted joints
    smpl_model = smplx.create(model_path=smpl_model_path, model_type='smpl', gender=gender)
    output = smpl_model(betas=betas, body_pose=pred_pose[:, 3:], global_orient=pred_pose[:, :3], return_verts=True)
    pred_joints = output.joints.detach().cpu().numpy()[:, :num_joints, :]  # Extract 24 joints
```
